-- Schema for the Adaptive Coding & DSA Learning Platform. Mirrors docs/CONTRACT.md section 3.
--
-- Why explicit DDL instead of letting Hibernate generate it: the schema is part of the
-- contract and must be readable on its own; Hibernate only VALIDATES it (ddl-auto: validate).
-- Why IF NOT EXISTS everywhere: this file runs on every startup and Postgres data persists.
-- Why VARCHAR(n) instead of TEXT for long strings: H2 maps TEXT to CLOB, which Hibernate's
-- validator rejects for a String field; a large VARCHAR behaves the same on both databases.
-- Why enums are VARCHAR + CHECK: readable in plain SQL, portable, and the DB itself rejects typos.

CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name  VARCHAR(50) NOT NULL UNIQUE,
    created_at    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- id is NOT generated: 1..10 is the fixed topic order and also the HLR one-hot index (id - 1).
CREATE TABLE IF NOT EXISTS topics (
    id    BIGINT      PRIMARY KEY,
    name  VARCHAR(40) NOT NULL UNIQUE,
    slug  VARCHAR(40) NOT NULL UNIQUE,
    CONSTRAINT ck_topics_id CHECK (id BETWEEN 1 AND 10)
);

CREATE TABLE IF NOT EXISTS topic_prerequisites (
    topic_id         BIGINT NOT NULL REFERENCES topics (id),
    prerequisite_id  BIGINT NOT NULL REFERENCES topics (id),
    PRIMARY KEY (topic_id, prerequisite_id),
    -- A prerequisite must come earlier in the fixed order; this makes a cycle impossible at the DB level.
    CONSTRAINT ck_prereq_earlier CHECK (prerequisite_id < topic_id)
);

CREATE TABLE IF NOT EXISTS problems (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id              BIGINT         NOT NULL REFERENCES topics (id),
    title                 VARCHAR(120)   NOT NULL,
    slug                  VARCHAR(120)   NOT NULL UNIQUE,
    difficulty            VARCHAR(10)    NOT NULL,
    statement             VARCHAR(20000) NOT NULL,
    input_format          VARCHAR(4000)  NOT NULL,
    output_format         VARCHAR(4000)  NOT NULL,
    starter_code          VARCHAR(20000) NOT NULL,
    time_limit_ms         INTEGER        NOT NULL DEFAULT 2000,
    -- NULL until calibrated with the reference solution; while NULL, SUBOPTIMAL is never assigned.
    optimal_runtime_ms    INTEGER,
    target_solve_seconds  INTEGER        NOT NULL,
    CONSTRAINT ck_problems_difficulty CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD')),
    CONSTRAINT ck_problems_time_limit CHECK (time_limit_ms > 0),
    CONSTRAINT ck_problems_optimal    CHECK (optimal_runtime_ms > 0),
    CONSTRAINT ck_problems_target     CHECK (target_solve_seconds > 0)
);
CREATE INDEX IF NOT EXISTS ix_problems_topic ON problems (topic_id);

CREATE TABLE IF NOT EXISTS test_cases (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id               BIGINT          NOT NULL REFERENCES problems (id),
    tag                      VARCHAR(10)     NOT NULL,
    ordinal                  INTEGER         NOT NULL,
    -- 1,000,000 chars leaves room for LARGE inputs (e.g. 10^5 integers) on both databases.
    input                    VARCHAR(1000000) NOT NULL,
    expected_output          VARCHAR(1000000) NOT NULL,
    -- Lets a curator say "failing THIS test means X" when the tag alone is too coarse.
    error_category_override  VARCHAR(30),
    CONSTRAINT uq_test_cases_problem_ordinal UNIQUE (problem_id, ordinal),
    CONSTRAINT ck_test_cases_tag CHECK (tag IN ('SAMPLE', 'EDGE', 'BOUNDARY', 'LARGE')),
    CONSTRAINT ck_test_cases_ordinal CHECK (ordinal >= 1),
    CONSTRAINT ck_test_cases_override CHECK (error_category_override IN (
        'SYNTAX_COMPILATION', 'OFF_BY_ONE', 'MISSED_EDGE_CASE', 'WRONG_ALGORITHM',
        'STATE_TRANSITION', 'BAD_COMPLEXITY', 'SUBOPTIMAL'))
);

CREATE TABLE IF NOT EXISTS attempts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT         NOT NULL REFERENCES users (id),
    problem_id          BIGINT         NOT NULL REFERENCES problems (id),
    code                VARCHAR(65535) NOT NULL,
    verdict             VARCHAR(25)    NOT NULL,
    passed_count        INTEGER        NOT NULL,
    total_count         INTEGER        NOT NULL,
    -- Max runtime over LARGE tests; compared with problems.optimal_runtime_ms for SUBOPTIMAL.
    large_runtime_ms    INTEGER,
    -- Client-measured (problem opened -> submit); feeds speed_vs_target. NULL if the client didn't send it.
    time_spent_seconds  INTEGER,
    submitted_at        TIMESTAMP      NOT NULL,
    CONSTRAINT ck_attempts_verdict CHECK (verdict IN (
        'ACCEPTED', 'WRONG_ANSWER', 'COMPILE_ERROR', 'RUNTIME_ERROR', 'TIME_LIMIT_EXCEEDED')),
    CONSTRAINT ck_attempts_counts CHECK (passed_count >= 0 AND passed_count <= total_count),
    CONSTRAINT ck_attempts_time   CHECK (time_spent_seconds >= 0)
);
CREATE INDEX IF NOT EXISTS ix_attempts_user_time ON attempts (user_id, submitted_at);

CREATE TABLE IF NOT EXISTS error_events (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- UNIQUE enforces "at most one error_event per submission".
    attempt_id            BIGINT       NOT NULL UNIQUE REFERENCES attempts (id),
    user_id               BIGINT       NOT NULL REFERENCES users (id),
    -- Copied from the problem so the weakness profile can group by topic without a join.
    topic_id              BIGINT       NOT NULL REFERENCES topics (id),
    error_category        VARCHAR(30)  NOT NULL,
    -- NULL only for SYNTAX_COMPILATION (no test ran).
    failed_tag            VARCHAR(10),
    failed_test_case_id   BIGINT REFERENCES test_cases (id),
    -- Simple class name of the exception for RUNTIME_ERROR, e.g. ArrayIndexOutOfBoundsException.
    exception_type        VARCHAR(120),
    occurred_at           TIMESTAMP    NOT NULL,
    CONSTRAINT ck_error_events_category CHECK (error_category IN (
        'SYNTAX_COMPILATION', 'OFF_BY_ONE', 'MISSED_EDGE_CASE', 'WRONG_ALGORITHM',
        'STATE_TRANSITION', 'BAD_COMPLEXITY', 'SUBOPTIMAL')),
    CONSTRAINT ck_error_events_tag CHECK (failed_tag IN ('SAMPLE', 'EDGE', 'BOUNDARY', 'LARGE'))
);
CREATE INDEX IF NOT EXISTS ix_error_events_user ON error_events (user_id, occurred_at);

-- One row per (user, topic), created lazily on the first submission or self-rating in that topic.
CREATE TABLE IF NOT EXISTS topic_state (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT           NOT NULL REFERENCES users (id),
    topic_id           BIGINT           NOT NULL REFERENCES topics (id),
    correct_count      INTEGER          NOT NULL DEFAULT 0,
    wrong_count        INTEGER          NOT NULL DEFAULT 0,
    -- NULL until the first attempt (a mean over zero attempts is undefined).
    mean_difficulty    DOUBLE PRECISION,
    last_practiced_at  TIMESTAMP,
    half_life_days     DOUBLE PRECISION,
    self_rating        INTEGER,
    CONSTRAINT uq_topic_state_user_topic UNIQUE (user_id, topic_id),
    CONSTRAINT ck_topic_state_counts     CHECK (correct_count >= 0 AND wrong_count >= 0),
    CONSTRAINT ck_topic_state_difficulty CHECK (mean_difficulty BETWEEN 1 AND 3),
    CONSTRAINT ck_topic_state_half_life  CHECK (half_life_days > 0),
    CONSTRAINT ck_topic_state_rating     CHECK (self_rating BETWEEN 1 AND 5)
);

-- Only overall numbers are stored; per-topic readiness is always computed live.
CREATE TABLE IF NOT EXISTS readiness_snapshots (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT    NOT NULL REFERENCES users (id),
    taken_at             TIMESTAMP NOT NULL,
    overall_self_rating  DOUBLE PRECISION,
    overall_computed     DOUBLE PRECISION,
    gap                  DOUBLE PRECISION,
    CONSTRAINT ck_snapshots_self     CHECK (overall_self_rating BETWEEN 1 AND 5),
    CONSTRAINT ck_snapshots_computed CHECK (overall_computed BETWEEN 0 AND 100)
);
CREATE INDEX IF NOT EXISTS ix_snapshots_user_time ON readiness_snapshots (user_id, taken_at);

-- Curated links only. Filled by resources.sql (supplied separately); NULL topic_id = generic for the category.
CREATE TABLE IF NOT EXISTS resources (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id        BIGINT REFERENCES topics (id),
    error_category  VARCHAR(30)  NOT NULL,
    title           VARCHAR(200) NOT NULL,
    url             VARCHAR(500) NOT NULL,
    source          VARCHAR(10)  NOT NULL,
    rank            INTEGER      NOT NULL,
    CONSTRAINT ck_resources_category CHECK (error_category IN (
        'SYNTAX_COMPILATION', 'OFF_BY_ONE', 'MISSED_EDGE_CASE', 'WRONG_ALGORITHM',
        'STATE_TRANSITION', 'BAD_COMPLEXITY', 'SUBOPTIMAL')),
    CONSTRAINT ck_resources_source CHECK (source IN ('GFG', 'YOUTUBE')),
    CONSTRAINT ck_resources_rank   CHECK (rank >= 1)
);
CREATE INDEX IF NOT EXISTS ix_resources_lookup ON resources (error_category, topic_id);
